### ISSUE TITLE
`astropy.units` for inputs?

### ISSUE THREAD

**Issue by TomWagg** [tobin-wainer/TESS_Cluster_Project#9]
@tobin-wainer thoughts on using `astropy.units` for inputs like radius, location, age etc? We can then convert them internally and just use the values in the same way but it lets people use any input that way. (Could also still allow a float input and assume a certain unit in that case)

**Comment by tobin-wainer** [comment]
So, you are saying that the user would need to specify what units they are inputting and the class would then convert to what we want? And the default float assumes some units?

**Comment by TomWagg** [comment]
Yeah exactly! They can still not use astropy units if they want, but the option would be there

**Comment by tobin-wainer** [comment]
Yeah, that sounds amazing! Then in the docs we just say what the default units are.

**Comment by TomWagg** [comment]
Cool, let's do it 😎
